### ISSUE TITLE
How can I get the paragraphs of each article?

### ISSUE THREAD

**Issue by qroam** [lgresearch/QASA#1]
In your QASA paper, it mentioned that the retrieval (pre-processing) step and the associative selection subtask are both done on paragraph level. And the dataset json file you provided also contains ``evidential_info`` contexts which are paragraphs from the article, but the full paragraph list is not provided. 
So I wonder how can I recover the list of paragraphs of each article in QASA dataset, if I would like to work on with it? Looking forward if you can kindly help me

**Comment by dasolhwang** [comment]
Hi, 

We only provide code that would provide access to the full text of the paper.
If you need, you can use the [src/get_paragraphs.py](https://github.com/lgresearch/QASA/blob/main/src/get_paragraphs.py) script.
Thanks :)
